version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - apt-get update -y && apt-get install -y latexmk texlive-latex-extra
      - cd static
      - npm ci
      - npm t
      - sh ../ci/scripts/build.sh
      - aws s3 cp build s3://$BUCKET --cache-control max-age=$CACHE_MAX_AGE --acl public-read --recursive
artifacts:
  files:
    - "**/*"
