version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update -y && apt-get install -y latexmk texlive-latex-extra
      - cd static
      - npm ci
  build:
    commands:
      - npm t
      - sh ../ci/scripts/build.sh
      # - aws s3 sync build s3://$BUCKET --cache-control max-age=$CACHE_MAX_AGE --acl public-read --delete
artifacts:
  files:
    - "**/*"
