Transform: AWS::Serverless-2016-10-31
Description: CloudFront resources for my personal website
Parameters:
  Domain:
    Description: Domain name to point at this environment
    Type: String
  BucketName:
    Description: Name of the S3 bucket where the static content lives
    Type: String
    AllowedValues:
      - website-test-bucket-bucket-1xdczqfmnh8ti
      - website-live-bucket-bucket-1j4uos3fih02k
Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          MinTTL: 60
          DefaultTTL: 600
          MaxTTL: 3600
          TargetOriginId: BucketOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: BucketOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Sub "${BucketName}.s3-website-eu-west-1.amazonaws.com"
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:008356366354:certificate/daab8ecf-3314-4a73-a05b-e14fc91be6a2
          SslSupportMethod: sni-only
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref Domain
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: Z3GMV07UUM9S0H
