Transform: AWS::Serverless-2016-10-31
Description: CloudFront resources for my personal website
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - live
    Description: The infrastructure environment
  Domain:
    Description: Domain name to point at this environment
    Type: String
  BucketName:
    Description: Name of the S3 bucket where the static content lives
    Type: String
    AllowedValues:
      - website-test-bucket-bucket-nexpgm1osjww
      - website-test-bucket-bucket-nexpgm1osjww
Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          MinTTL: 60
          DefaultTTL: 600
          MaxTTL: 3600
          TargetOriginId: BucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: !Ref ViewerRequestFunction.Version
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: BucketOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Sub "${BucketName}.s3-website-eu-west-1.amazonaws.com"
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:008356366354:certificate/daab8ecf-3314-4a73-a05b-e14fc91be6a2
          SslSupportMethod: sni-only
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref Domain
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: Z3GMV07UUM9S0H
  ViewerRequestFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${Environment}-viewer-request-policy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::blah/*
  ViewerRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/viewer-request
      Handler: src/index.handler
      Runtime: nodejs12.x
      FunctionName: !Sub "${Environment}-personal-website-viewer-request"
      MemorySize: 192
      AutoPublishAlias: alias
      Role: !GetAtt ViewerRequestFunctionRole.Arn
      Timeout: 3
