Description: Pipeline for my personal website
Parameters:
  BasePolicyArn:
    Type: String
    Description: IAM Policy ARN of the base CodeBuild policy
    Default: arn:aws:iam::008356366354:policy/core-infrastructure-global-CodeBuildBaseManagedPolicy-FWV7ZO5N6AGF
  CodePipelineCloudFormationRoleArn:
    Type: String
    Description: IAM Role ARN to be assumed by CodePipeline to perform CloudFormation actions
    Default: arn:aws:iam::008356366354:role/core-infrastructure-globa-CodePipelineCloudFormati-1NF00Q6M6OVE1
  BuildArtifactsBucketEUWest1Name:
    Type: String
    Description: S3 Bucket name where build artifacts are stored in eu-west-1
    Default: core-infrastructure-eu-w-buildartifactsbucketeuwe-12d2acmozch84
  BuildArtifactsBucketUSEast1Name:
    Type: String
    Description: S3 Bucket name where build artifacts are stored in us-east-1
    Default: core-infrastructure-us-e-buildartifactsbucketusea-cmkndmg3ty11
  CodePipelineExecutionRoleArn:
    Type: String
    Description: IAM Role ARN to be assumed by CodePipeline when executing
    Default: arn:aws:iam::008356366354:role/core-infrastructure-globa-CodePipelineBaseRoleB458-161XPXE39XXUL
  TestBucketName:
    Description: Name of the S3 bucket for the test environment
    Type: String
    Default: website-test-bucket-bucket-1xdczqfmnh8ti
  LiveBucketName:
    Description: Name of the S3 bucket for the live environment
    Type: String
    Default: website-live-bucket-bucket-1j4uos3fih02k
Resources:
  TestWebsiteCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref BasePolicyArn
      Policies:
        - PolicyName: test-website-codebuild-s3-policy
          PolicyDocument:
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:DeleteObject
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${TestBucketName}/*"
              - Action:
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${TestBucketName}"

  TestWebsiteCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref BuildArtifactsBucketEUWest1Name
        Path: /artifacts/personal-website-test/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds and deploys my personal website to test
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET
            Value: !Ref TestBucketName
            Type: PLAINTEXT
          - Name: ENVIRONMENT
            Value: test
            Type: PLAINTEXT
          - Name: CACHE_MAX_AGE
            Value: "600"
            Type: PLAINTEXT
      Name: personal-website-build-and-deploy-website-test
      ServiceRole: !GetAtt TestWebsiteCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  LiveWebsiteCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref BasePolicyArn
      Policies:
        - PolicyName: live-website-codebuild-policy
          PolicyDocument:
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:DeleteObject
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${LiveBucketName}/*"
              - Action:
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${LiveBucketName}"

  LiveWebsiteCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref BuildArtifactsBucketEUWest1Name
        Path: /artifacts/personal-website-live/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds and deploys my personal website to live
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET
            Value: !Ref LiveBucketName
            Type: PLAINTEXT
          - Name: ENVIRONMENT
            Value: live
            Type: PLAINTEXT
          - Name: CACHE_MAX_AGE
            Value: "3600"
            Type: PLAINTEXT
      Name: personal-website-build-and-deploy-website-live
      ServiceRole: !GetAtt LiveWebsiteCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStores:
        - Region: eu-west-1
          ArtifactStore:
            Type: S3
            Location: !Ref BuildArtifactsBucketEUWest1Name
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Ref BuildArtifactsBucketUSEast1Name
      Name: personal-website
      RestartExecutionOnUpdate: true
      RoleArn: !Ref CodePipelineExecutionRoleArn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !ImportValue core-infrastructure-eu-west-1-codestar-github-connection-arn
                FullRepositoryId: alexchesters/cheste.rs
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Deploy-To-Test
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Update-CloudFront-Stack
              Region: us-east-1
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: website-test-cloudfront
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/cloudfront.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/cloudfront/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Update-Bucket-Stack
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: website-test-bucket
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/bucket.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/bucket/test.json
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 2
              Name: Build-And-Deploy-Website-Content
              Configuration:
                ProjectName: !Ref TestWebsiteCodeBuildProject
        - Name: Deploy-To-Live
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Update-Cloudfront-Stack
              Region: us-east-1
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: website-live-cloudfront
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/cloudfront.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/cloudfront/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Update-Bucket-Stack
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: website-live-bucket
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/bucket.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/bucket/live.json
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 2
              Name: Build-And-Deploy-Website-Content
              Configuration:
                ProjectName: !Ref LiveWebsiteCodeBuildProject
